### ISSUE TITLE
docker-compose lack of schedule config

### ISSUE THREAD

**Issue by oguzhancelikarslan** [labbati/pgdump2s3#1]
We need to automate something. can you add a scheduling feature to automate DB back-up?

**Comment by labbati** [comment]
I had completely lost the notification about this message. You probably do not need it anymore 😃, but for future reference: scheduling should not be a concern of this image. This image should be `docker run ...` by a cronjob, or you can use on of k8s' scheduling facilities.

This image is meant to be used for short leaved containers.
